### ISSUE TITLE
Notice id parameter is not present in the Unity initialize method

### ISSUE THREAD

**Issue by pmerlet-at-didomi** [didomi/unity#10]
If I am correct, when calling Didomi.initialize, the "noticeId" argument is not present. 
This argument should be present (but optional), so sdk clients can target a specific notice instead of the default for the app.

Reference: https://developers.didomi.io/cmp/mobile-sdk/ios/reference#initialize

**Comment by ibrahimseyhun** [comment]
resolved in [pull request](https://github.com/didomi/unity/pull/12)
