### ISSUE TITLE
Errors after importing the project

### ISSUE THREAD

**Issue by ykaplunskyi** [didomi/unity#25]
Hi guys, have you ever tested your release before releasing it??
Just imported a project and guess what - **compiler** error

![image](https://user-images.githubusercontent.com/73309449/150126661-e57b190e-c8fb-4444-9c5a-6781f6a33aef.png)

are you kidding? 
SDK: latest https://github.com/didomi/unity/releases/tag/v1.1.0
Unity: 2019.3.12
Platform: Android

**Comment by pmerlet-at-didomi** [comment]
Hello, is it possible for you to add iOS build support to your Unity version if it is not already added? It can be done in the "Installs" section of the Unity Hub.

Doing this may be enough to solve the issue: https://forum.unity.com/threads/solved-cloud-build-fails-when-using-postprocessbuild.956397/
