### ISSUE TITLE
Update latest version of native SDK

### ISSUE THREAD

**Issue by nghuuhieu1994** [didomi/unity#35]
Hi @pmerlet-at-didomi, please make a release of Unity SDK to use latest native SDK.

**Comment by pmerlet-at-didomi** [comment]
Hello, we are currently working on an update with the latest native SDKs. You can expect it this week.

**Comment by pmerlet-at-didomi** [comment]
The release with updated native SDKs versions is available: https://github.com/didomi/unity/releases/tag/v1.5.0
