### ISSUE TITLE
JCenter dependency unable to resolve

### ISSUE THREAD

**Issue by nghuuhieu1994** [didomi/unity#42]
Hi @pmerlet-at-didomi, we can't build the project on Android platform because of the dependency 'com.iab.gdpr_android:gdpr_android:1.0.1' cannot download from jcenter.

Trace:
```
Could not find com.iab.gdpr_android:gdpr_android:1.0.1.
     Searched in the following locations:
       - https://maven.google.com/com/iab/gdpr_android/gdpr_android/1.0.1/gdpr_android-1.0.1.pom
```

**Comment by pmerlet-at-didomi** [comment]
Hello @nghuuhieu1994 , this dependency should no longer be needed, we forgot to remove it from Unity sdk release.

It will be removed in next release, in the meantime you can remove it from your project: in file `Assets/Plugins/Didomi/Editor/PostProcessor.cs` , line 136.

**Comment by nghuuhieu1994** [comment]
thank @pmerlet-at-didomi
