### ISSUE TITLE
UNITY SDK several issues

### ISSUE THREAD

**Issue by TijsVdV** [didomi/unity#5]
While implementing the UNITY sdk into our project (DeSlimsteMens, SBS) i have encountered several bugs:

**IOS**
****

1) the PostProcessor script in unity has a typo on line 45: **FRAMERWORK_SEARCH_PATHS** instead of **FRAMEWORK_SEARCH_PATHS**. This causes the property to be added to user defined properties instead of the correct one.

2) In **Didomi.mm** the function showPreferences calls a none existing function, it should be calling this:
[[Didomi shared] showPreferencesWithController:(nil) view:(ViewsPurposes)];

3) When creating a project **(Unity 2019.4.8f1)** with only the Didomi sdk in it and building for iOS , not changing anything in the settings, the build crashes on launch with these errors:

<img width="583" alt="Screenshot 2020-09-24 at 11 47 13" src="https://user-images.githubusercontent.com/71819762/94129516-baf02200-fe5b-11ea-8a41-d3e5e18ab2a4.png">

4) The framework added to the UnityPackage is build for the simulator and not for iOS itself. Is this intended? I have to copy the framework from the iOS documentation to get the correct one. If this is intended this should atleast be mentioned in the documentation.

**Android**
********

The whole build process is intended for people who export to an Android project. Most of the time (in my experience) unity developers don't want this. I have been able to remove all the post build steps for android so the build process also works with building an APK/AAB directly. If you are interested in this code feel free to contact me at tijs@triangle-factory.be.

**Comment by ibrahimseyhun** [comment]
Thanks for your feedback. 
All issues resolved in the release [v1.0.3-beta]( https://github.com/didomi/unity/releases/tag/v1.0.3-beta)
