### ISSUE TITLE
Use release version for Android embedded sdk

### ISSUE THREAD

**Issue by pmerlet-at-didomi** [didomi/unity#6]
The Android SDK currently embedded in Unity plugin is in debug mode. We should use the release version instead (in particular, because the debug SDK requests Didomi staging environment instead of prod)

If we update to the last version at the same time, the release aar can be found directly on mavenCentral : https://search.maven.org/artifact/io.didomi.sdk/android/1.34.0/aar > download

**Comment by ibrahimseyhun** [comment]
Android SDK debug version replaced with the release version of Android SDK. The update done in the Unity Plugin release v.1.0.3

**Comment by philemonmerlet** [comment]
Thanks @ibrahimseyhun . Did you push these changes on master? I don't see the commits.

**Comment by ibrahimseyhun** [comment]
I only replaced the UnityPackage in the release v1.0.3 of the project 8
days ago. I just did a new commit to the master to replace the  aar file in
the source code.
