### ISSUE TITLE
Add new methods from native SDKs

### ISSUE THREAD

**Issue by pmerlet-at-didomi** [didomi/unity#8]
Support new methods recently added to native sdks: 

- onError
https://developers.didomi.io/cmp/mobile-sdk/android/reference#onerror
https://developers.didomi.io/cmp/mobile-sdk/ios/reference#onerror

- setUserStatus (replaces setUserConsentStatus, which should be deprecated)
https://developers.didomi.io/cmp/mobile-sdk/android/reference#setuserstatus (2 possible parameters list)
https://developers.didomi.io/cmp/mobile-sdk/ios/reference#setuserstatus (also 2 possible parameters list, even if only one is referenced in the doc at the moment)

- getUserLegitimateInterestStatusForPurpose
https://developers.didomi.io/cmp/mobile-sdk/android/reference#getuserlegitimateintereststatusforpurpose
https://developers.didomi.io/cmp/mobile-sdk/ios/reference#getuserlegitimateintereststatusforpurpose

- getUserLegitimateInterestStatusForVendor
https://developers.didomi.io/cmp/mobile-sdk/android/reference#getuserlegitimateinterestforvendor
https://developers.didomi.io/cmp/mobile-sdk/ios/reference#getuserlegitimateinterestforvendor

- getUserLegitimateInterestForVendorAndRequiredPurposes
https://developers.didomi.io/cmp/mobile-sdk/android/reference#getuserlegitimateintereststatusforvendorandrequiredpurposes
https://developers.didomi.io/cmp/mobile-sdk/ios/reference#getuserlegitimateintereststatusforvendorandrequiredpurposes

**Comment by ibrahimseyhun** [comment]
resolved in [pull request](https://github.com/didomi/unity/pull/9)
