### ISSUE TITLE
ConsentChanged event does not work in Unity, iOS

### ISSUE THREAD

**Issue by g0dzZz-coder** [didomi/unity#93]
Hey! I think plugin `v2.1.0` does not trigger the `ConsentChanged` event specifically on _**iOS**_. 
Its does not work in first accept and status update scenarios.
We are using the following code to subscribe to the event:
```cscharp
_eventListener = new DidomiEventListener();
_eventListener.ConsentChanged += onConsentChanged;
instance.AddEventListener(_eventListener);
```
And on _**iOS**_, the handler is not being called in the same scenarios where it is called on Android. It seems like a bug.

**Comment by pmerlet-at-didomi** [comment]
Hello @g0dzZz-coder , thanks for your feedback. We will have a look at the issue.

**Comment by g0dzZz-coder** [comment]
I have now discovered that the `DidomiEventListener.Ready` handler is also never called on `iOS`

**Comment by g0dzZz-coder** [comment]
Hello. I discovered an issue on my end after reviewing the code of your wrapper. 
The signature of the `AddEventListener` method misled me, as it seemed like I could register multiple listeners. Maybe it should have been named `SetEventListener`.
It's strange that the issue only occurred on iOS, but oh well)
I kept single instance of `DidomiEventListener` and the issue was resolved.

**Comment by pmerlet-at-didomi** [comment]
Hello, glad to hear that you found a solution. We take note that the method name can be misleading, we have to find a way to change it without breaking the API.

If you still need a structure similar to several listeners, you can keep a reference to your listener and add several handlers to it:

```
        eventListener.ConsentChanged += EventListener_ConsentChanged1;
        eventListener.ConsentChanged += EventListener_ConsentChanged2;
```
